services:
  - type: web
    name: sistemapulperia-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGODB_URI
        value: <your-mongodb-uri>
      - key: JWT_SECRET
        value: <your-jwt-secret>
      - key: PORT
        value: 10000